tasks:
  - name: "update apt packages"
    become: yes
    apt:
      update_cache: yes
      when: ansible_os_family == "Debian"
      ignore_errors: True

  - name: "upgrade packages"
    become: yes
    apt:
      upgrade: yes
      when: ansible_os_family == "Debian"
      ignore_errors: True